version: "3"

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_list
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asdf
  server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres