# Generated by Django 5.0.7 on 2024-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Deleted')])),
                ('todo_id', models.IntegerField(verbose_name='해당 Todo의 ID')),
                ('user_id', models.IntegerField(verbose_name='해당 Todo의 사용자')),
                ('status', models.IntegerField(choices=[(0, 'done'), (1, 'not_yet')], verbose_name='완료 상태')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(help_text='마감 기한')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, 'done'), (1, 'not_yet')], verbose_name='완료 상태'),
        ),
    ]
